### ISSUE TITLE
[question] apis don't seem to be published: 404 in apiservice status

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/apiserver-builder-alpha#585]
hello, I believe I have successfully deployed my first apiserver built with apiserver-builder-beta. My apiservice status looks as this:
```yaml
  conditions:
    - type: Available
      status: 'False'
      lastTransitionTime: '2021-03-29T19:40:49Z'
      reason: FailedDiscoveryCheck
      message: >-
        failing or missing response from
        https://10.129.0.48:8443/apis/vault.redhatcop.redhat.io/v1alpha1: bad
        status from
        https://10.129.0.48:8443/apis/vault.redhatcop.redhat.io/v1alpha1: 404
```
I interpret this as being the master api calling that path on the my apiserver and getting a 404. 
On a good note, if I make that call with a simple curl command I get a 403, so authn/authz delegation works.  
The question is why the 404/not found? 
I am publishing the apiserver like this:
```golang
	err := builder.APIServer.
		WithResourceAndHandler(&redhatcopv1alpha1.SecretEngine{}, filepath.NewJSONFilepathStorageProvider(&redhatcopv1alpha1.SecretEngine{}, "data")). // namespaced resource
		WithLocalDebugExtension().
		Execute()
```
and the SecretEngine resource is defines the follow gvr:
```golang
func (in *SecretEngine) GetGroupVersionResource() schema.GroupVersionResource {
	return schema.GroupVersionResource{
		Group:    "vault.redhatcop.redhat.io",
		Version:  "v1alpha1",
		Resource: "secretengines",
	}
}
```
what am I doing wrong?
